version: '3'
services:
  backend:
    image: node:20-alpine
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
